### ISSUE TITLE
Coloring of material design

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/hass-poc-configurator#6]
Text and icons are all mint/green colored.

**Comment by jmart518** [comment]
This has been fixed in my copy, I'll be uploading it shortly

<img width="337" alt="screen shot 2017-02-06 at 6 45 31 am" src="https://cloud.githubusercontent.com/assets/1509640/22649398/f3aa65a4-ec37-11e6-8d89-cd057d844185.png">
<img width="334" alt="screen shot 2017-02-06 at 6 45 19 am" src="https://cloud.githubusercontent.com/assets/1509640/22649399/f3aba2b6-ec37-11e6-9316-3c3b81a31881.png">
